version: '3'
services:
  app1:        # same name is used in nginx.config
    build: ./app1
    ports:
      #- "5001:5000"
      - "5000"  # not specifying the host port. We are supposed to use the load balancer anyway!
  app2:       # same name is used in nginx.config
    build: ./app2
    ports:
      #- "5002:5000"
      - "5000"  # not specifying the host port. We are supposed to use the load balancer anyway!
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
